export const gmailEmails = {
  message: [
    {
      id: "email_001",
      from: "priya.sharma@example.in",
      to: "support@trendmart.in",
      subject: "Refund for defective shoes — Order TM-8899",
      date: "2025-10-25T10:45:00+05:30",
      category: "refund_request",
      order_id: "TM-8899",
      amount: 1999.0,
      currency: "INR",
      reason: "Product damaged",
      status: "requested",
      attachments: ["shoe_damage.jpg"],
      body: "Hi team, I received the shoes I ordered yesterday but they are torn on one side. Please initiate a refund or replacement for Order TM-8899. Regards, Priya.",
      language: "en",
      tone: "polite",
    },
    {
      id: "email_002",
      from: "info@cityfitness.com",
      to: "subscribers@cityfitness.com",
      subject: "🎉 Grand Opening of Our New Gym — Exclusive Offers Inside!",
      date: "2025-11-01T08:30:00+05:30",
      category: "announcement",
      attachments: [],
      body: "We are thrilled to announce the opening of our new CityFitness branch at Lakeview Mall! Get 50% off on your first month when you join before November 15th. Visit cityfitness.com/join for more details.",
      language: "en",
      tone: "enthusiastic",
    },
    {
      id: "email_003",
      from: "rahul.kumar@example.com",
      to: "billing@softserve.io",
      subject: "Incorrect billing — need refund for last month",
      date: "2025-10-29T15:00:00+05:30",
      category: "refund_request",
      order_id: "INV-7765",
      amount: 499.0,
      currency: "INR",
      reason: "Charged after cancellation",
      status: "requested",
      attachments: ["invoice_october.pdf"],
      body: "Hi team, I canceled my subscription last month but was still billed ₹499 on Oct 25th. Kindly refund the amount. Attached invoice for reference.",
      language: "en",
      tone: "firm",
    },
    {
      id: "email_004",
      from: "newsletter@greenleaffoods.com",
      to: "customers@greenleaffoods.com",
      subject: "New Product Launch — Organic Protein Bars!",
      date: "2025-10-27T12:00:00+05:30",
      category: "announcement",
      attachments: ["product_banner.jpg"],
      body: "Introducing our newest Organic Protein Bars, made with 100% natural ingredients. Available in stores and online starting today! Try them and stay healthy.",
      language: "en",
      tone: "friendly",
    },
    {
      id: "email_005",
      from: "maria.gomez@example.com",
      to: "support@travelnow.com",
      subject: "Request refund for canceled flight TN-99231",
      date: "2025-11-03T09:20:00-05:00",
      category: "refund_request",
      order_id: "TN-99231",
      amount: 412.5,
      currency: "USD",
      reason: "Flight canceled by airline",
      status: "requested",
      attachments: ["cancellation_notice.pdf"],
      body: "Dear team, my flight TN-99231 on Nov 2 was canceled. Please process a full refund to my card. Thank you, Maria.",
      language: "en",
      tone: "neutral",
    },
    {
      id: "email_006",
      from: "support@techgear.eu",
      to: "all-customers@techgear.eu",
      subject: "⚠️ Important: Scheduled Maintenance on Nov 6",
      date: "2025-11-04T17:00:00+02:00",
      category: "announcement",
      attachments: [],
      body: "Dear customers, TechGear systems will undergo scheduled maintenance on November 6, 2:00 AM – 5:00 AM CET. During this time, website and order tracking may be unavailable. We appreciate your patience.",
      language: "en",
      tone: "informative",
    },
    {
      id: "email_007",
      from: "alex.nguyen@example.com",
      to: "feedback@freshbasket.com",
      subject: "Suggestion about delivery timing",
      date: "2025-10-30T14:15:00+07:00",
      category: "feedback",
      attachments: [],
      body: "Hi FreshBasket, I love your service but deliveries in my area usually come late in the evening. It would be great if you could add more afternoon slots. Thanks! — Alex",
      language: "en",
      tone: "constructive",
    },
    {
      id: "email_008",
      from: "events@creativex.com",
      to: "creators@creativex.com",
      subject: "🚀 Join Our Annual Creator Meetup 2025!",
      date: "2025-11-02T09:00:00+05:30",
      category: "announcement",
      attachments: ["event_flyer.png"],
      body: "We’re hosting our 2025 Creator Meetup in Mumbai on December 10th! Join industry experts, network with fellow creators, and explore the future of digital content. RSVP at creativex.com/meetup.",
      language: "en",
      tone: "excited",
    },
    {
      id: "email_009",
      from: "meera.jain@example.in",
      to: "support@bookbazaar.com",
      subject: "Order not delivered — request refund",
      date: "2025-10-31T20:40:00+05:30",
      category: "refund_request",
      order_id: "BBZ-1188",
      amount: 599.0,
      currency: "INR",
      reason: "Package lost",
      status: "requested",
      attachments: [],
      body: "Hello BookBazaar, my order BBZ-1188 has not been delivered even after 10 days. Please initiate a refund or resend the book. Regards, Meera.",
      language: "en",
      tone: "polite",
    },
    {
      id: "email_010",
      from: "contact@universityupdates.edu",
      to: "students@universityupdates.edu",
      subject: "University closed on November 8 for Diwali holidays",
      date: "2025-11-05T09:30:00+05:30",
      category: "announcement",
      attachments: [],
      body: "Dear students, the university will remain closed from November 8 to 10 on account of Diwali. Regular classes will resume on November 11. Have a happy and safe festival!",
      language: "en",
      tone: "formal",
    },
  ],
};
